## Definimod el tipo de base de datos
quarkus.datasource.db-kind=postgresql
## Usuario con el que se conecta a la base de datos
quarkus.datasource.username=postgres
## Contraseña del usuario con el que se conecta a la base de datos
quarkus.datasource.password=postgres
## URL de conexión a la base de datos
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/trabajo_final
## Sincroización de la base de datos con el codigo
quarkus.hibernate-orm.database.generation=update
## Mostrar las consultas SQL en la consola
quarkus.hibernate-orm.log.sql=true